### ISSUE TITLE
problem when installing vuldash

### ISSUE THREAD

**Issue by alvaradovex** [talsoft/vuldash#1]
When I go to the link localhost/vuldash/dashboard/  I receive a 404 error with the login.
How can I fix that error? What was my mistake?

**Comment by talsoft** [comment]
Hi, can you give me the configuration of virtualhost apache and content of file .htaccess? What is your apache and php version?

**Comment by talsoft** [comment]
Hi, please test this configuration:

mkdir /var/www/vuldash
cd /var/www/vuldash
git clone https://github.com/talsoft/vuldash.git dashboard

Settings Mysql account
nano dashboard/application/config/database.php

Change Virtualhost
nano /etc/apache2/sites-enabled/000-default.conf

Into VirtualHost Change
DocumentRoot --> /var/www/vuldash
Directory  -->  <Directory /var/www/vuldash>

**Comment by talsoft** [comment]
Then restart Apache and access with url: http://localhost/dashboard

**Comment by alvaradovex** [comment]
Hi Mr. Leandro, here is the problem:
[image: image.png]

My OS is Windows Server 2008 R2 64bits.

Thanks for your help.

**Comment by talsoft** [comment]
Hi, I can't see the image error. You can upload again?

**Comment by alvaradovex** [comment]
[image: Vuldash001.PNG]

**Comment by talsoft** [comment]
The screen not apear. You can copy and paste the error? You are use Apache + Mysql?

**Comment by alvaradovex** [comment]
I'm using Window Server 2008R2 64bits, with Xampp 5.6.23 (localhost:
Apache/2.4.33 PHP7.2.6). When I go to the link
http://localhost/vuldash/dashboard/, it show: *Object not found!* (*Error
404*) and the URL change to /localhost/vuldash/dashboard/login (Apache and
MySQL services are running).

[image: image.png]

**Comment by talsoft** [comment]
Thanks, Vuldash run in php 5.6  and try to.

- In the folder dashboard, copy the vuldash files and directory 
- In the virtualhost apache setting documentroot -> vuldash directory only
- Go to url http://localhost/dashboard

see the example step in the [https://github.com/talsoft/vuldash/blob/master/README.md](https://github.com/talsoft/vuldash/blob/master/README.md )

**Comment by agaggini** [comment]
I tried it on a xampp with php on win7 and it worked perfectly. You should verify in .htacces that RewriteRule is well written.

**Comment by alvaradovex** [comment]
Hi Mr. Andres. I already changed the PHP version to 5.6.23, but the error
persists. When you say "verify .htacces" you mean the Apache or the Vuldash?

**Comment by alvaradovex** [comment]
Good morning. Yes, as it is, and the error is still 404.

**Comment by talsoft** [comment]
I think that you have a error in your enviroment. You can install vuldash in debian, kali linux. Andres was able to install it on a xampp with php on win7 and it worked perfectly. You should verify in .htaccess that RewriteRule is well written.
The .htaccess  file in the folder ../vuldash/dashboard/ and check the modules php installed with rewrite enable.
 Apache php 5.6 (modules php5.6-gd php5.6-json php5.6-mbstring php5.6-xsl php5.6-zip)

**Comment by alvaradovex** [comment]
Mr. Leandro, Mr. Andres, using Windows Server 2008 R22 64 bits, Xampp, PHP
5.6.23 (path xampp/htdocs/vuldash/dashboard - even with the version of PHP
7.0.5), with the browser firefox and the http
url://localhost/vuldash/dashboard/, rewriting the .htaccess, I managed to
access the page.
Thanks for your valuable support. We will keep in touch.

**Comment by talsoft** [comment]
perfect that works
regards

**Comment by jorgepg92** [comment]
Hi Mr. Alvarado you could share the htaccess settings

**Comment by talsoft** [comment]
Yes, there is:

<IfModule mod_rewrite.c>
    RewriteEngine On
    #RewriteBase /dashboard
    RewriteCond %{HTTPS} off
    RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
    RewriteBase /
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php/$1 [L]
</IfModule>





Que tenga un excelente día,

Suscríbase a nuestro canal de *Youtube
<https://www.youtube.com/channel/UCnO026Qq-DHx3yHjL6jTO9g>* y a visite
nuestro portal de entrenamiento https://learn.talsoft.com.ar

-- 
Saludos Cordiales,
Ing. Leandro Gabriel Ferrari
CEO - TalSoft TS
Mar del Plata, Buenos Aires, Argentina
Oficina: + 54 9 223 5719033
Skype: leandroferrari.talsoft
www.talsoft.com.ar

*Facebook <https://www.facebook.com/talsoftsrl/> | Twitter
<https://twitter.com/talsoft> | Newsletter <http://eepurl.com/cq0c_j> |
Youtube <https://www.youtube.com/channel/UCnO026Qq-DHx3yHjL6jTO9g> |
Linkedin <https://www.linkedin.com/company-beta/309631/>*

**Comment by fabianalvarez317** [comment]
Hola al realizar la instalacion siguiendo las intsrucciones y ejecutandolo con todos los requisitos tecnicos y al ingresar a local host me redirecciona a http://localhost/dashboard/login pero me indica que no existe el archivo login

**Comment by talsoft** [comment]
Hola Fabian, cuando aparece ese error es posible algún error en el virtualhost o como estan las carpetas del vuldash.
Has podido chequear:

    DocumentRoot --> /var/www/vuldash
    Directory --> <Directory /var/www/vuldash>

El código fuente tiene que quedar en **/var/www/vuldash/dashboard**   pero el virtual host debe apuntar a **/var/www/vuldash**

Otro tema es el siguiente si tenés habilitado el modulo rewrite:
    a2enmod rewrite
    services apache2 restart

Cuando realizar la peticion: [http://localhost/dashboard/login]( http://localhost/dashboard/login) , la carpeta login no existe en realidad lo toma el controlador del frameworlk y te redirigue a la primer pagina de login.

**Comment by fabianalvarez317** [comment]
hola que tal? aun no puedo pero me acabo de dar cuenta que cuando arranco el apache me presenta este error "Invalid command 'Directory', perhaps misspelled or defined by a module not included in the server configuration" por lo que veo tiene que ver con el virtualhost
