### ISSUE TITLE
more visibility

### ISSUE THREAD

**Issue by noraj** [talsoft/vuldash#4]
On github you can look for project by tags (named topics on github). Example: https://github.com/topics/pentest

For a better visibility you can add tags, like:

- pentest
- pentest-dashboard
- vulnerability
- vulnerability-dashboard
- dashboard
- cybersecurity
- infosec
- etc.

https://help.github.com/en/articles/classifying-your-repository-with-topics

**Comment by talsoft** [comment]
Hi Alexandre. Thank you!. I will add this tags in the project.
Best regards,
Leandro
